### ISSUE TITLE
don't connect gaps

### ISSUE THREAD

**Issue by dirkraft** [blacklocus/anvil#28]
There's a big difference between no-data and "I'm not sure if this is data or flot is just connecting the dots"

There's a flot plugin that might work

http://joeloughton.com/blog/web-applications/flot-plugins-x-gap-threshold/

Set gaps threshold based on aggregation period, e.g. if aggregation periods of 15 minutes is selected,
then a continuous set of data would have a point every 15 minutes. A gap is any consecutive pair of points more than 15 minutes apart.

**Comment by chadbay** [comment]
nice, this was hard to do with nvd3

**Comment by amcclosky** [comment]
:+1:
