### ISSUE TITLE
add commas to the Y axis numbers

### ISSUE THREAD

**Issue by rholder** [blacklocus/anvil#32]
It's hard to tell the difference between 100000 and 1000000 without commas. I don't know if this still applies, but something on this page might do the trick: http://stackoverflow.com/questions/5968212/comma-separated-numbers-for-an-axis-in-flot

**Comment by dirkraft** [comment]
Note to selves, consider http://numeraljs.com/ for further future polish. Make sure locale support still works, e.g. 123,456.78 vs 123.456,78

**Comment by rholder** [comment]
:+1:
