### ISSUE TITLE
explicitly set x-axis range

### ISSUE THREAD

**Issue by dirkraft** [blacklocus/anvil#35]
Currently the x-axis is the min/max datetime of data points. If the window is set to 12 hours, but the series only go as far as 2 hours back, the x-axis starts 2 hours ago, which can be confusing since the window is set to 12.

Explicitly set the range of the x-axis to [now - window, now]

**Comment by Brent-Knight-BL** [comment]
@dirkraft fixed this already:

<img width="983" alt="screen shot 2016-07-08 at 2 16 42 pm" src="https://cloud.githubusercontent.com/assets/9805790/16698947/a46721bc-4516-11e6-811b-b3d33221deae.png">

**Comment by Brent-Knight-BL** [comment]
Closing #35
